### ISSUE TITLE
2017-02-01-blackhistorymonth.txt and 2017-02-01-black-history-month.txt are transcriptions of the same speech

### ISSUE THREAD

**Issue by ellisvalentiner** [hrbrmstr/orangetext#3]

**Comment by hrbrmstr** [comment]
thx. will fix when i include today's radio address

**Comment by hrbrmstr** [comment]
thx again. taken care of in https://github.com/hrbrmstr/orangetext/commit/f5ec86164021570fd537d747a63fc6713b22774c
